spring.application.name=TallerEvaluativo_DOSW-1

spring.data.mongodb.uri=mongodb+srv://robinsonnunezp_db_user:Chispitas_7_@fintech.lovfhfs.mongodb.net/?retryWrites=true&w=majority&appName=Fintech

spring.data.mongodb.database=fintech